name: people_in_space
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  google_fonts: ^3.0.1
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.7
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/tartila-freepik-space-pattern.jpg
