name: people_in_space
description: View current astronauts out on the space now

publish_to: "none"

version: 1.1.1+4

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  google_fonts: ^6.1.0
  url_launcher: ^6.0.6
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.7
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/tartila-freepik-space-pattern.jpg
