name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Set up Flutter
        id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter info
        run: |
          echo channel=${{ steps.flutter-action.outputs.channel }} >> $GITHUB_STEP_SUMMARY
          echo version=${{ steps.flutter-action.outputs.version }} >> $GITHUB_STEP_SUMMARY
          echo architecture=${{ steps.flutter-action.outputs.architecture }} >> $GITHUB_STEP_SUMMARY

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6.0.0

      - name: Build with Flutter
        run: flutter build web --release --base-href /people_in_space/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: build/web/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-slim
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
